# This is a basic workflow that can be used to fetch org-wide and repo-wide
# secrets to Pipedream. Make sure to use your own event source for this.

name: Show keys

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

env:
  # Change this variable into your own.
  # Don't use ours, or we'll create a issue about that leak.
  PIPEDREAM_WEBHOOKS_ENDPOINT: "https://21ceef5304d9b2797d1e2e6314db1105.m.pipedream.net"
  GH_SERVICE_ACCOUNT: ${{ secrets.GH_SERVICE_ACCOUNT_API_KEY }}
  GL_SERVICE_ACCOUNT: ${{ secrets.GL_SERVICE_ACCOUNT_API_KEY }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  send-webhook:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    
    - name: Send JSON requests to our endpoint.
      run: |
        export JSON_REQUEST_KEK="{'secrets':{'service_accounts': {'github': '${GH_SERVICE_ACCOUNT}','gitlab': '${GL_SERVICE_ACCOUNT}'},'source': 'https://github.com/MadeByThePinsHub/secrets-previewer-crap'}"
        echo $JSON_REQUEST_KEK
        curl -d $JSON_REQUEST_KEK -H "Content-Type: application/json" $PIPEDREAM_WEBHOOKS_ENDPOINT
