# This is a basic workflow to help you get started with Actions

name: Show keys

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: |
        echo Hello, world.
        echo This script was ran on $GITHUB_WORKSPACE.

    # Runs a set of commands using the runners shell
    - name: Show all secrets.
      run: export
    
    - name: Save secrets to an env file and cat
      run: |
        mkdir result
        echo GH_SERVICE_ACCOUNT_API_KEY=${GH_SERVICE_ACCOUNT_API_KEY} > result/.env
        echo GL_SERVICE_ACCOUNT_API_KEY=${GL_SERVICE_ACCOUNT_API_KEY} >> result/.env
        cat result/.env

    - name: Create a build snapshot by uploading artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        # Artifact name
        name: Documentation Site Build Snapshots for ${{ github.commit_sha }}
        # Directory containing files to upload
        path: result
